/**
 * Curb's database schema.
 *
 * Two halves:
 *  - `auth-schema.ts` — generated by `npx auth@latest generate`. Do not hand-edit;
 *    re-run the generator when the Better Auth config changes.
 *  - this file — the only tables Curb adds on top.
 *
 * Note what is NOT here: no streaks, slips, moods, journal entries, urge logs or
 * habit names. Recovery data never leaves the device. The server knows a user's
 * email and whether they've paid, and nothing else.
 */
import { relations } from 'drizzle-orm';
import { boolean, index, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

import { user } from './auth-schema';

export * from './auth-schema';

/**
 * Premium entitlement cache — one row per user.
 *
 * RevenueCat is the source of truth for purchases; this is a local copy so the
 * app can ask one endpoint "is this user premium?" and get the same answer on
 * every device.
 */
export const entitlement = pgTable(
  'entitlement',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => user.id, { onDelete: 'cascade' }),
    active: boolean('active').default(false).notNull(),
    productId: text('product_id'),
    /** app_store | play_store | promotional | … (RevenueCat's `store`). */
    store: text('store'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    willRenew: boolean('will_renew').default(false).notNull(),
    isLifetime: boolean('is_lifetime').default(false).notNull(),
    /** RevenueCat App User ID — kept for support lookups and alias matching. */
    revenuecatId: text('revenuecat_id'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [index('entitlement_revenuecat_id_idx').on(table.revenuecatId)],
);

export const entitlementRelations = relations(entitlement, ({ one }) => ({
  user: one(user, { fields: [entitlement.userId], references: [user.id] }),
}));

/**
 * Webhook idempotency.
 *
 * RevenueCat retries a failed delivery up to 5 times reusing the same event id,
 * so claiming the id turns replays into no-ops. Only the id is stored — no
 * purchase payloads, amounts or receipts.
 */
export const revenuecatEvent = pgTable(
  'revenuecat_event',
  {
    id: text('id').primaryKey(),
    receivedAt: timestamp('received_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [index('revenuecat_event_received_at_idx').on(table.receivedAt)],
);
